-- local venv = require('venv-selector')
--
-- venv.setup({
--   auto_refresh = false,
--   search_venv_managers = true,
--   search_workspace = true,
--   search = true,
--   parents = 2,
--   fd_binary_name = "fd",
--   path = "~/.venv/"
-- })
